[package]
name = "rsx_parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
dioxus = { path = "D:/Users/Desktop/github/dioxus", features = ["web", "ssr"] }
syn = "1.0"
quote = "1.0"